limit_req_zone $binary_remote_addr zone=php:10m rate=5r/s;

server {
    listen  80 default_server;
    server_name  mac.2yyc.com;
    root   /www/gen;
    index  index.php index.html index.htm;
    #charset koi8-r;
    
    access_log /dev/null;
    access_log  /var/log/nginx/2yyc.access.log  main;
    error_log  /var/log/nginx/2yyc.error.log  warn;
    
    #error_page  404              /404.html;
    error_page 404 = @notfound;
    location @notfound {
        return 301 https://www.12377.cn/jbzn.html?tab=4;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ [^/]\.php(/|$) {
        limit_req zone=php burst=10 nodelay;
        fastcgi_pass   php82:9000;
        include        fastcgi-php.conf;
        include        fastcgi_params;
    }

    location ~* /(wp-|admin|phpmyadmin|\.env|\.git|backup|test) {
        return 444;
    }

    location = /favicon.ico {
      log_not_found off;
      access_log off;
    }


    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}